insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (101,'SNAP','approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (102,'SNAP','approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (103,'SNAP','denied','Ishtiyaq','isti@123','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (104,'SNAP','denied','saurabh','saurabh@123','expired');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (105,'CCAP','approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (106,'CCAP','approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (107,'CCAP','denied','Ishtiyaq','isti@123','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (108,'CCAP','denied','saurabh','saurabh@123','expired');


insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (109,'Medicaid','approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (110,'Medicaid','approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (111,'Medicaid','denied','Ishtiyaq','isti@123','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (112,'Medicaid','denied','saurabh','saurabh@123','expired');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (113,'Medicare','approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (114,'Medicare','approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (115,'Medicare','denied','Ishtiyaq','isti@123','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (116,'Medicare','denied','saurabh','saurabh@123','expired');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (117,'QHP','approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (118,'QHP','approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (119,'QHP','denied','Ishtiyaq','isti@123','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENIAL_REASN) values (120,'QHP','denied','saurabh','saurabh@123','expired');




